# -*- coding: utf-8 -*-
"""#Task02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10OU2Y3wC7kzQF_TS-rHGeccDrWL0i1QL

# **PRODIGY INFOTECH - DATA SCIENCE INTERNSHIP**

### **Name : Gauri Baban Dhembare**

### **Task - 02**

Perform data cleaning and exploratory data analysis (EDA) on a dataset of ,your choice, such as a titanic dataset from kaggle, Explore the relationships between variables and identify patterns and trends in the data.

# **Loading Required Libraries**
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

"""# **Loading Dataset**"""

tips = sns.load_dataset('tips')
tips

"""# **Exploratory Data Analysis**"""

tips.head()

tips.tail()

tips.describe()

tips.info()

tips.dtypes

tips.size

tips.columns

"""### **Cleaning the data**"""

print(tips.isnull().sum())

"""### **Statistical Analysis**"""

tips["total_bill"].sum()

tips["total_bill"].mean()

tips["total_bill"].median()

tips["total_bill"].mode()

tips["total_bill"].std()

tips["total_bill"].count()

"""### **Explore the data**"""

import matplotlib.pyplot as plt
import seaborn as sns

# Distribution of 'total_bill'
sns.histplot(tips['total_bill'], kde=True, color="blue")
plt.title('Distribution of Total Bill')
plt.show()

# Distribution of 'tip'
sns.histplot(tips['tip'], kde=True, color="blue")
plt.title('Distribution of Tip')
plt.show()

# Distribution of 'size'
sns.histplot(tips['size'], discrete=True, color="blue")
plt.title('Distribution of Size')
plt.show()

# Count plot of 'sex'
sns.countplot(data=tips, x='sex', color="blue")
plt.title('Gender Distribution')
plt.show()

# Count plot of 'smoker'
sns.countplot(data=tips, x='smoker', color="blue")
plt.title('Smoker Distribution')
plt.show()

# Count plot of 'time'
sns.countplot(data=tips, x='time', color="blue")
plt.title('Time of Day Distribution')
plt.show()

# Count plot of 'day'
sns.countplot(data=tips, x='day', color="blue")
plt.title('Day of Week Distribution')
plt.show()

"""### **Visualize Relationships and Trends**"""

# Joint plot of total bill vs tip with regression line
sns.jointplot(data=tips, x='total_bill', y='tip', kind='reg',color="blue")
plt.title('Total Bill vs Tip with Regression Line')
plt.show()

# Scatter plot of total bill vs tip
sns.scatterplot(data=tips, x='total_bill', y='tip', color="blue")
plt.title('Total Bill vs Tip')
plt.show()

# Box plot of tips by smoker
sns.boxplot(data=tips, x='smoker', y='tip', color="blue")
plt.title('Tips by Smoker Status')
plt.show()

# Box plot of tips by gender
sns.boxplot(data=tips, x='sex', y='tip', color="blue")
plt.title('Tips by Gender')
plt.show()

# Box plot of tips by time
sns.boxplot(data=tips, x='time', y='tip', color="blue")
plt.title('Tips by Time of Day')
plt.show()

# Box plot of tips by day
sns.boxplot(data=tips, x='day', y='tip', color="blue")
plt.title('Tips by Day of the Week')
plt.show()

# Box plot of tips by size of party
sns.boxplot(data=tips, x='size', y='tip', color="blue")
plt.title('Tips by Size of Party')
plt.show()

"""## **Conclusion**"""

# Plot Total Bill vs Tip
plt.figure(figsize=(8, 6))
sns.scatterplot(data=tips, x='total_bill', y='tip',color="blue")
plt.title('Total Bill vs Tip')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.show()

# Gender vs Tip
plt.figure(figsize=(8, 6))
sns.boxplot(data=tips, x='sex', y='tip',color="blue")
plt.title('Tips by Gender')
plt.xlabel('Gender')
plt.ylabel('Tip')
plt.show()

# Smoker vs Tip
plt.figure(figsize=(8, 6))
sns.boxplot(data=tips, x='smoker', y='tip', color="blue")
plt.title('Tips by Smoker Status')
plt.xlabel('Smoker')
plt.ylabel('Tip')
plt.show()

# Day vs Tip
plt.figure(figsize=(8, 6))
sns.boxplot(data=tips, x='day', y='tip', color="blue")
plt.title('Tips by Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Tip')
plt.show()

# Time vs Tip
plt.figure(figsize=(8, 6))
sns.boxplot(data=tips, x='time', y='tip', color="blue")
plt.title('Tips by Time of Day')
plt.xlabel('Time of Day')
plt.ylabel('Tip')
plt.show()

# Size vs Tip
plt.figure(figsize=(8, 6))
sns.boxplot(data=tips, x='size', y='tip', color="blue")
plt.title('Tips by Size of Party')
plt.xlabel('Size of Party')
plt.ylabel('Tip')
plt.show()

"""## **Conclusions from EDA**

1) There is a positive correlation between the total bill and the tip amount.

2) Female servers tend to receive slightly higher tips compared to male servers.

3) There is no significant difference in tips between smokers and non-smokers.

4)Tips are generally higher on weekends (Saturday and Sunday) compared to weekdays.

5)Tips are generally higher during dinner time compared to lunch.

"""