# -*- coding: utf-8 -*-
"""Tast#1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LYEpopORpMpMZkUeaQcc966n6T50jZsp

# **PRODIGY INFOTECH - DATA SCIENCE INTERNSHIP**

**Name : Gauri Baban Dhembare**

**Task - 01**

Create a bar chart or histogram to visualize the distribution of a categorical or continuous variable, such as the distribution of ages or genders in a population.

# **Loading Modules**
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

"""# **Loading Dataset**"""

import pandas as pd
db=pd.read_csv("/content/Bike_Buyers.csv")
db

db.plot()

"""## **Understanding and Analysing the data**"""

db.head()

db.tail()

db.describe()

db.info()

db.dtypes

db.isnull().sum()

db.size

db.columns

db['Age'].unique()

db['Gender'].unique()

db['Age'].value_counts()

db['Gender'].value_counts()

"""# **Data Visualization**"""

import matplotlib.pyplot as plt
import seaborn as sns
plt.xlabel("Gender", color="blue")
plt.ylabel("Age", color='blue')
plt.title("Bar Plot", color="red")
sns.barplot(data=db, x="Gender", y="Age",color="yellow")

import matplotlib.pyplot as plt
import seaborn as sns
sns.countplot(x='Gender', data=db, color="blue")
plt.title('Gender Distribution')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
db['IncomeCategory'] = pd.cut(db['Income'], bins=[0, 30000, 60000, 90000, 120000], labels=['0-30k', '30k-60k', '60k-90k', '90k-120k'])
sns.countplot(x='IncomeCategory', hue='Purchased Bike', data=db)
plt.title('Bike Purchases by Income Level')
plt.xlabel('Income Level')
plt.ylabel('Count')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
sns.countplot(x='Occupation', hue='Purchased Bike', data=db)
plt.title('Bike Purchases by Occupation')
plt.xlabel('Occupation')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
sns.countplot(x='Education', data=db, color="blue")
plt.title('Education Level Distribution')
plt.xlabel('Education Level')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""## Histogram for Age"""

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10, 6))
sns.histplot(db['Age'], kde=True, bins=20, color="blue")
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

"""## Histogram for Income"""

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10, 6))
sns.histplot(db['Income'], kde=True, bins=20, color="blue")
plt.title('Income Distribution')
plt.xlabel('Income')
plt.ylabel('Frequency')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")

# Create a histogram plot of age, separated by gender
plt.figure(figsize=(10, 6))
sns.histplot(data=db, x='Age', hue='Gender', multiple='stack', kde=True)

# Add titles and labels
plt.title('Age Distribution by Gender')
plt.xlabel('Age')
plt.ylabel('Frequency')

# Show the plot
plt.show()